// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import OrderItemModalController from "./order_item_modal_controller"
application.register("order-item-modal", OrderItemModalController)

import RestaurantServerController from "./restaurant_server_controller"
application.register("restaurant-server", RestaurantServerController)
